name: React App CI CD
# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [main]
    pull_request:
        branches: [main]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    react-app-workflow:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x
            - name: ci
              run: npm ci
            - name: format
              run: npm run fix:prettier
                  echo "âœ¨ Passed Prettier"
            - name: lint
              run: npm run lint
                  echo "ðŸ“¸ Safe Eslint"
            - name: test
              run: npm test
                  echo "ðŸ§ª Tests Passed"
            - name: build
              run: npm run build
                  echo "ðŸš€ Safe Build"
            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v3
              with:
              name: assets-to-download
              path: ./build/
              retention-days: 5
              run: echo "âœ… Uploaded Artifacts"